### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by bthe** [Hafro/geo#1]
1) delete directory www and old
2) move content of directory pkg to root
3) "reverse engineer" directory man so that it is compatible with roxygen2

**Comment by sigurdurthorjonsson** [comment]
'geo' now installs from github, after tidying and Rd2roxygen on the package by Einar and Bjarki (1 & 2) finished and 3) underway:

3contd) finish roxygenizing the help files (helpfiles for groups of functions weren't caught)
4) settle on branching and versioning strategy
5) start preparing 1.5-0 for submission to CRAN?
