### ISSUE TITLE
geo_1.5-0

### ISSUE THREAD

**Issue by sigurdurthorjonsson** [Hafro/geo#3]
Aim for release of version 1.5 on CRAN before the summer. Suggest the team add to the development branch incrementing the minor-version until we have 1.5 CRAN-ready. Todo's could include:
- Add vignette(s).
- Improve function documentation, possibly grouping together related
  functions.
- Remove redundant contours and make necessary changes to
  gbplot. Currently 'gbplot' does not plot a 2000 m isobath.
  - Double check version 1.4-5 especially removal of 'inside' and 'geoarea.old'.
- Improve dataset documentation (in 'dataset_doc.R')
- Add crucial datasets and connectivity to other packages such as
  'gisland', making it possible for the user to set up e.g. coastlines
  and bathymetry for an arbirtrary region of interest.
- Setting parameters and such, could that be improved upon?

**Comment by einarhjorleifsson** [comment]
hmm, date in NEWS should be yyyy-mm-dd, not yyyy-dd-mm

**Comment by einarhjorleifsson** [comment]
done

**Comment by einarhjorleifsson** [comment]
done, again
